verify tag format

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -15,6 +15,30 @@ workflows:
       - activate-ssh-key@4:
           run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
       - git-clone@4: {}
+      - get-pubspec-version-and-build-number@1: {}
+      - script@1:
+          inputs:
+            - content: >-
+                #!/usr/bin/env bash
+
+                # fail if any commands fails
+                set -e
+                # debug log
+                set -x
+
+                echo "tag $BITRISE_GIT_TAG"
+                echo "version $PUBSPEC_VERSION_NAME"
+                echo "version code $PUBSPEC_BUILD_NUMBER"
+
+                if [ x$BITRISE_GIT_TAG == "x" ]; then
+                  echo "No tag found. Exiting"
+                  exit 1
+                fi
+
+                if [ $BITRISE_GIT_TAG != "${PUBSPEC_VERSION_NAME}_${PUBSPEC_BUILD_NUMBER}" ]; then
+                  echo "Project version does not match tag"
+                  exit 1
+                fi
       - certificate-and-profile-installer@1: {}
       - flutter-installer@0: {}
       - cache-pull@2: {}
@@ -50,8 +74,8 @@ workflows:
           inputs:
             - webhook_url: $SLACK_WEBHOOK_URL
             - channel: '#deployment'
-            - message: 'Successful deployment \U0001F4AA'
-            - message_on_error: 'Failed to deploy \U0001F631'
+            - message: Successful deployment \U0001F4AA
+            - message_on_error: Failed to deploy \U0001F631
   primary:
     steps:
       - activate-ssh-key@4:
@@ -69,7 +93,7 @@ workflows:
       - deploy-to-bitrise-io@1: {}
       - cache-push@2: {}
       - slack@3:
-          run_if: ".IsBuildFailed"
+          run_if: .IsBuildFailed
           inputs:
             - webhook_url: $SLACK_WEBHOOK_URL
             - channel: '#mobile'
