Custom avd manager script

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -121,12 +121,49 @@ workflows:
         run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
     - git-clone@4: {}
     - cache-pull@2: {}
-    - 'git::https://github.com/DEalog/steps-avd-manager.git@master':
-        title: AVD manager
+    - script@1:
         inputs:
-        - api_level: '30'
-        - start_command_flags: '-camera-back none -camera-front none'
-        - profile: '23'
+        - content: >-
+            #!/usr/bin/env bash
+
+            # fail if any commands fails
+
+            set -e
+
+            # debug log
+
+            set -x
+
+
+            # write your script here
+
+            sudo $ANDROID_HOME/tools/bin/sdkmanager --update
+
+            $ANDROID_HOME/tools/bin/sdkmanager --install "emulator"
+
+            $ANDROID_HOME/tools/bin/sdkmanager --install
+            "system-images;android-30;google_apis;x86"
+
+            echo "no" | $ANDROID_HOME/tools/bin/avdmanager --verbose create avd
+            --force --name "pixel3a" --device "pixel_3a" --package
+            "system-images;android-30;google_apis;x86" --tag "google_apis" --abi
+            "x86"
+
+            $ANDROID_HOME/emulator/emulator-headless @pixel3a -no-boot-anim
+            -netdelay none -no-snapshot -wipe-data -verbose -show-kernel
+            -no-audio -gpu swiftshader_indirect -no-snapshot &> /tmp/log.txt &
+
+            sleep 160
+    # - avd-manager@1:
+    #     inputs:
+    #     - api_level: '26'
+    #     - profile: '18'
+    # - 'git::https://github.com/DEalog/steps-avd-manager.git@master':
+    #     title: AVD manager
+    #     inputs:
+    #     - api_level: '30'
+    #     - start_command_flags: '-camera-back none -camera-front none'
+    #     - profile: '23'
     - wait-for-android-emulator@1: {}
     - script@1:
         inputs:
